name: CI/CD for library-front

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REPOSITORY: vkdahdk/library-front

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile  # This specifies we're using the Dockerfile in the root
        push: true
        tags: |
          ${{ env.DOCKER_REPOSITORY }}:latest
          ${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}

    - name: Update Kubernetes manifests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email front@users.noreply.github.com
        sed -i 's|image: .*|image: ${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}|' applications/library-front/deployment.yaml
        git add applications/library-front/deployment.yaml
        git commit -m "Update library-front image to ${{ github.sha }}"
        git push